ALTER TABLE public.blessings ALTER COLUMN side DROP NOT NULL;
ALTER TABLE public.blessings ALTER COLUMN side SET DEFAULT NULL;
ALTER TABLE public.memories ALTER COLUMN side DROP NOT NULL;
ALTER TABLE public.memories ALTER COLUMN side SET DEFAULT NULL;
